sudo: true
os: trusty
cache: false

before_install:
- cd $HOME
- wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.5.0/pmd-bin-6.5.0.zip
- unzip pmd-bin-6.5.0.zip
- alias pmd="$HOME/pmd-bin-6.5.0/bin/run.sh pmd"

script:
- ls
- echo $HOME
- /home/travis/pmd-bin-6.5.0/bin/run.sh pmd -d . -f text -rulesets apex-ruleset
